name: 'Terrateam Workflow'
on:
  workflow_dispatch:
    inputs:
      work-token:
        description: 'Work Token'
        required: true
      api-base-url:
        description: 'API Base URL'
      environment:
        description: 'Environment in which to run the action'
        type: environment

jobs:
  terrateam:
    permissions: # Required to pass credentials to the Terrateam action
      id-token: write
      contents: read
    runs-on: terrateam-self-hosted
    timeout-minutes: 1440
    name: Terrateam Action
    environment: '${{ github.event.inputs.environment }}'
    steps:
      - uses: actions/checkout@v4
      - name: Run Terrateam Action
        uses: docker://ghcr.io/terrateamio/action:v1
        with:
          args: >
            "${{ github.event.inputs.work-token }}"
            "${{ github.event.inputs.api-base-url }}"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARIABLES_CONTEXT: ${{ toJson(vars) }}
